### PR TITLE
Add source RPM manifest to build.

### PR DESCRIPTION
**Pull request by johnelse**
Partial fix for CA-66143.

### CODE REVIEW

**Comment by xen-git** [comment]
### johnelse/stunnel@adea35fa92505ff0f69770179e64355c10dbb17c &#8658; xen-org/stunnel@55c1c0325e26b54b377e80125c6c166ee1d0b9a8: Build succeeded. Can merge pull request.

**Comment by xen-git** [comment]
### johnelse/stunnel@8e88341f2c45fe042468b78dfc7692c9f50ed90d &#8658; xen-org/stunnel@55c1c0325e26b54b377e80125c6c166ee1d0b9a8: Build succeeded. Can merge pull request.

**Comment by jonludlam** [comment]
@xen-git Approved.

**Comment by xen-git** [comment]
### johnelse/stunnel@8e88341f2c45fe042468b78dfc7692c9f50ed90d &#8658; xen-org/stunnel@55c1c0325e26b54b377e80125c6c166ee1d0b9a8: Build succeeded. Pull request merged.

**Pull request merged**
