### PR TITLE
This is more close to my understanding of the idle condition.

### PR DESCRIPTION
**Pull request by zli**
It might help the 12 hours timeout issue (which occasionally happens when we pull the plug of a running host during communication), though this would be fairly difficult to verify.

Signed-off-by: Zheng Li zheng.li@eu.citrix.com

### CODE REVIEW

**Comment by xen-git** [comment]
### zli/stunnel@28d4cb5664e471763de81ebfa094396348b03c82 &#8658; xen-org/stunnel@8e88341f2c45fe042468b78dfc7692c9f50ed90d: Build succeeded. Can merge pull request.

**Comment by zli** [comment]
I'm not familiar with stunnel either. There is no way to clearly understand the details given the limited time I can spend on it. So the modification is purely based on my basic understanding of these variables (which consequently based on reading the comments and small pieces of code here and there) :

Stunnel bridges two sockets: ssl socket and local socket
- sock_wr: local socket is open for write
- sock_rd: local socket is open for read
- sock_ptr: input buffer of local socket (to be pass to ssl socket)
- ssl_wr: ssl socket is open for write
- ssl_rd: ssl socket is open for read
- ssl_ptr: input buffer of ssl socket (to be pass to local socket)

so the modified condition 

(sock_wr && (ssl_rd || c->ssl_ptr)) || (ssl_wr && (sock_rd || c->sock_ptr))

means: if at least one direction of the bi-direction dataflow is possible, then use TIMEOUTidle (longest idle period) as poll waiting timeout, otherwise use TIMEOUTclose (period for verifying lost connection) as poll waiting timeout.

I still don't fully understand the original implementation. It could be that the author took advantage of some correlation between these variables. However it's confirmed elsewhere, in some cases, the default stunnel implementation might wait up to TIMEOUTidle period if the other side being powered off during communication.

I did some dev testing with the modified condition. It seemed to work as before (in cases where TIMEOUTclose and TIMEOUTidle should kick in). I also tried the host power off test, the stunnel aborted the connection in a short period. It was not as immediate as I expected: it took around 2 minutes (with large amount of data during tranfer), possible some other timeout (buffer? TCP?) became effective. Still, I'm not completely sure whether this means that the modification has fixed the problem or it's because the issue won't reproduce easily anyway :-(.

**Comment by robhoes** [comment]
Is this repo used anywhere?

@djs55 What should we do with this?

**Comment by djs55** [comment]
I think this repo is actually where we get stunnel from. If we're going to continue using stunnel then we should be tracking upstream more closely. I've been putting off looking at that because we probably should be using https://github.com/bumptech/stud which I believe is faster, especially in a 64-bit dom0:

http://vincent.bernat.im/en/blog/2011-ssl-benchmark.html

**Comment by euanh** [comment]
@zli: Do we still want this pull request?   We now configure stunnel to send idle keepalives, which should detect the case where the other end has hung up.  If we don't need this PR any more, please close it.

**Pull request closed without merging**
